import type { ToolCatalogItem } from "./types.ts"

type ToolInput = Pick<
  ToolCatalogItem,
  | "id"
  | "name"
  | "stageIds"
  | "categories"
  | "officialUrl"
  | "freeTierSummary"
  | "limitations"
  | "upgradeSignals"
  | "alternatives"
  | "sources"
> &
  Partial<
    Pick<
      ToolCatalogItem,
      | "entityTypes"
      | "regions"
      | "productTypes"
      | "skillLevels"
      | "lastVerifiedAt"
      | "verificationDays"
      | "status"
    >
  >

function tool(input: ToolInput): ToolCatalogItem {
  return {
    entityTypes: ["any"],
    regions: ["GLOBAL"],
    productTypes: ["any"],
    skillLevels: ["any"],
    lastVerifiedAt: "2026-07-12",
    verificationDays: 90,
    status: "active",
    ...input,
  }
}

export const REQUIRED_TOOL_IDS = [
  "google-trends",
  "product-hunt",
  "tally",
  "calendly",
  "figma",
  "github",
  "codex",
  "claude-code",
  "cursor",
  "supabase",
  "cloudflare-pages",
  "vercel",
  "stripe",
  "paddle",
  "lemon-squeezy",
  "wise-business",
  "cloudflare-web-analytics",
  "posthog",
  "sentry",
  "resend",
  "n8n",
  "make",
  "github-actions",
] as const

export const TOOL_CATALOG: ToolCatalogItem[] = [
  tool({
    id: "google-trends",
    name: "Google Trends",
    stageIds: ["discover"],
    categories: ["market-research"],
    officialUrl: "https://trends.google.com/trends/",
    freeTierSummary: "公开趋势研究工具，可免费查看相对搜索热度。",
    limitations: ["趋势热度不等于付费需求，必须结合访谈验证。"],
    upgradeSignals: ["需要更精细的关键词量级、广告或竞品数据。"],
    alternatives: ["product-hunt"],
    sources: [{ label: "Google Trends", url: "https://trends.google.com/trends/" }],
  }),
  tool({
    id: "product-hunt",
    name: "Product Hunt",
    stageIds: ["discover", "validate", "iterate"],
    categories: ["market-research", "launch"],
    officialUrl: "https://www.producthunt.com/",
    freeTierSummary: "浏览产品、评论和发布动态无需付费。",
    limitations: ["社区反馈偏早期采用者，不能代表全部目标客户。"],
    upgradeSignals: ["需要稳定的自有用户访谈和产品内行为数据。"],
    alternatives: ["google-trends"],
    sources: [{ label: "Product Hunt", url: "https://www.producthunt.com/" }],
  }),
  tool({
    id: "tally",
    name: "Tally",
    stageIds: ["validate"],
    categories: ["forms", "waitlist"],
    officialUrl: "https://tally.so/pricing",
    freeTierSummary: "免费方案覆盖多数表单、逻辑和响应收集需求。",
    limitations: ["品牌、团队协作和高级域名能力需核对付费方案。"],
    upgradeSignals: ["需要自定义域名、团队权限或更复杂的数据治理。"],
    alternatives: ["calendly"],
    sources: [{ label: "Tally Pricing", url: "https://tally.so/pricing" }],
  }),
  tool({
    id: "calendly",
    name: "Calendly",
    stageIds: ["validate"],
    categories: ["interviews", "scheduling"],
    officialUrl: "https://calendly.com/pricing",
    freeTierSummary: "免费方案适合一个基础访谈预约流程。",
    limitations: ["多事件类型、自动化和团队路由通常需要升级。"],
    upgradeSignals: ["访谈量增长或需要自动提醒和多成员分配。"],
    alternatives: ["tally"],
    sources: [{ label: "Calendly Pricing", url: "https://calendly.com/pricing" }],
  }),
  tool({
    id: "figma",
    name: "Figma",
    stageIds: ["mvp"],
    categories: ["prototype", "design"],
    officialUrl: "https://www.figma.com/pricing/",
    freeTierSummary: "Starter 免费方案适合个人原型和有限协作。",
    limitations: ["高级协作、分支和团队管理能力需要升级。"],
    upgradeSignals: ["设计文件和协作者数量开始阻碍交付。"],
    alternatives: ["github"],
    sources: [{ label: "Figma Pricing", url: "https://www.figma.com/pricing/" }],
  }),
  tool({
    id: "github",
    name: "GitHub",
    stageIds: ["mvp", "build", "deploy", "iterate"],
    categories: ["source-control", "planning"],
    officialUrl: "https://github.com/pricing",
    freeTierSummary: "Free 方案可创建公开和私有仓库并使用基础协作能力。",
    limitations: ["高级安全、规则和团队治理需要付费或资格。"],
    upgradeSignals: ["需要组织级权限、强制审查或高级安全扫描。"],
    alternatives: ["github-actions"],
    sources: [{ label: "GitHub Pricing", url: "https://github.com/pricing" }],
  }),
  tool({
    id: "codex",
    name: "Codex",
    stageIds: ["build"],
    categories: ["ai-coding"],
    officialUrl: "https://developers.openai.com/codex/",
    freeTierSummary: "无持久免费额度承诺；按当前 ChatGPT/API 方案核验。",
    limitations: ["需要人工审查代码、测试结果和权限边界。"],
    upgradeSignals: ["使用量、并行任务或团队治理超出当前方案。"],
    alternatives: ["claude-code", "cursor"],
    sources: [{ label: "OpenAI Codex", url: "https://developers.openai.com/codex/" }],
  }),
  tool({
    id: "claude-code",
    name: "Claude Code",
    stageIds: ["build"],
    categories: ["ai-coding"],
    officialUrl: "https://docs.anthropic.com/en/docs/claude-code/overview",
    freeTierSummary: "无持久免费额度承诺；按订阅或 API 使用方式核验。",
    limitations: ["模型生成代码必须经过测试、审查和最小权限控制。"],
    upgradeSignals: ["上下文、调用量或团队管理需要更高方案。"],
    alternatives: ["codex", "cursor"],
    sources: [{ label: "Claude Code Docs", url: "https://docs.anthropic.com/en/docs/claude-code/overview" }],
  }),
  tool({
    id: "cursor",
    name: "Cursor",
    stageIds: ["build"],
    categories: ["ai-coding", "ide"],
    officialUrl: "https://www.cursor.com/pricing",
    freeTierSummary: "Hobby 方案提供有限的编辑器与 AI 使用能力。",
    limitations: ["Agent 调用和高级模型用量受方案限制。"],
    upgradeSignals: ["免费调用不足以完成稳定开发周期。"],
    alternatives: ["codex", "claude-code"],
    sources: [{ label: "Cursor Pricing", url: "https://www.cursor.com/pricing" }],
  }),
  tool({
    id: "supabase",
    name: "Supabase",
    stageIds: ["backend"],
    categories: ["database", "auth", "storage"],
    officialUrl: "https://supabase.com/pricing",
    freeTierSummary: "免费方案包含 500 MB 数据库、50,000 MAU、1 GB 文件存储；闲置项目会暂停。",
    limitations: ["公开 schema 表必须启用 RLS；免费项目缺少生产级备份保障。"],
    upgradeSignals: ["需要不暂停、自动备份、更高数据库/存储/带宽配额。"],
    alternatives: ["cloudflare-pages"],
    sources: [
      { label: "Supabase Pricing", url: "https://supabase.com/pricing" },
      { label: "Secure the Data API", url: "https://supabase.com/docs/guides/api/securing-your-api" },
    ],
  }),
  tool({
    id: "cloudflare-pages",
    name: "Cloudflare Pages / Workers",
    stageIds: ["deploy", "backend", "automation"],
    categories: ["hosting", "edge-functions"],
    officialUrl: "https://developers.cloudflare.com/pages/platform/limits/",
    freeTierSummary: "免费方案适合静态站和小型边缘函数；额度以官方限制页为准。",
    limitations: ["静态导出与运行时函数边界需要在架构阶段明确。"],
    upgradeSignals: ["请求、构建、CPU 或存储需求超过免费限制。"],
    alternatives: ["vercel"],
    sources: [{ label: "Cloudflare Pages Limits", url: "https://developers.cloudflare.com/pages/platform/limits/" }],
  }),
  tool({
    id: "vercel",
    name: "Vercel",
    stageIds: ["deploy"],
    categories: ["hosting"],
    officialUrl: "https://vercel.com/pricing",
    freeTierSummary: "Hobby 方案适合个人和非商业试验，商业使用需核对条款。",
    limitations: ["商业项目、团队功能和更高资源需求可能需要付费。"],
    upgradeSignals: ["开始商业运营或达到 Hobby 使用边界。"],
    alternatives: ["cloudflare-pages"],
    sources: [{ label: "Vercel Pricing", url: "https://vercel.com/pricing" }],
  }),
  tool({
    id: "stripe",
    name: "Stripe",
    stageIds: ["payments"],
    categories: ["checkout", "subscriptions"],
    officialUrl: "https://stripe.com/global",
    entityTypes: ["hk-company", "sg-company", "us-company", "other-company"],
    regions: ["HK", "SG", "US", "SUPPORTED"],
    productTypes: ["any"],
    freeTierSummary: "通常按交易计费，无固定月费；地区和产品资格必须核验。",
    limitations: ["中国大陆不在 Stripe 直接开户支持地区列表；商户承担税务与争议责任。"],
    upgradeSignals: ["需要更复杂订阅、税务、风控或企业支持。"],
    alternatives: ["paddle", "lemon-squeezy"],
    verificationDays: 30,
    sources: [{ label: "Stripe Global Availability", url: "https://stripe.com/global" }],
  }),
  tool({
    id: "paddle",
    name: "Paddle",
    stageIds: ["payments"],
    categories: ["merchant-of-record", "subscriptions"],
    officialUrl: "https://developer.paddle.com/get-started/how-paddle-works/",
    freeTierSummary: "无固定免费额度；以交易费和当前商业审核为准。",
    limitations: ["仅适用于平台接受的软件/数字产品，供应商和产品都需审核。"],
    upgradeSignals: ["交易量使 MoR 综合费率高于自建税务与支付成本。"],
    alternatives: ["stripe", "lemon-squeezy"],
    verificationDays: 30,
    sources: [
      { label: "How Paddle Works", url: "https://developer.paddle.com/get-started/how-paddle-works/" },
      { label: "Paddle Supported Countries", url: "https://www.paddle.com/help/legal/sanctions/which-countries-are-supported-by-paddle" },
    ],
  }),
  tool({
    id: "lemon-squeezy",
    name: "Lemon Squeezy",
    stageIds: ["payments"],
    categories: ["merchant-of-record", "digital-products"],
    officialUrl: "https://docs.lemonsqueezy.com/help/getting-started/supported-countries",
    freeTierSummary: "无固定月费承诺；销售与提现按当前费率和支持地区核验。",
    limitations: ["商户需通过身份、产品和提现资格审核；支持国家会变化。"],
    upgradeSignals: ["需要更低综合费率或更复杂的企业合同能力。"],
    alternatives: ["paddle", "stripe"],
    verificationDays: 30,
    sources: [{ label: "Supported Countries", url: "https://docs.lemonsqueezy.com/help/getting-started/supported-countries" }],
  }),
  tool({
    id: "wise-business",
    name: "Wise Business",
    stageIds: ["payments"],
    categories: ["settlement", "multi-currency-account"],
    officialUrl: "https://wise.com/help/articles/2977974/can-my-business-use-wise",
    entityTypes: ["hk-company", "sg-company", "us-company", "other-company"],
    freeTierSummary: "无统一免费额度；开户、账户详情、换汇和收款费用按地区核验。",
    limitations: ["不是通用订阅支付网关；银行卡收款能力受地区和新客户可用性限制。"],
    upgradeSignals: ["需要完整订阅管理、税务代征或更广泛本地支付方式。"],
    alternatives: ["stripe", "paddle"],
    verificationDays: 30,
    sources: [
      { label: "Wise Business Eligibility", url: "https://wise.com/help/articles/2977974/can-my-business-use-wise" },
      { label: "Wise Payment Links", url: "https://wise.com/help/articles/4qr3kkvIQlHNiD8BegEB4u/getting-paid-to-your-wise-business-by-payment-link" },
    ],
  }),
  tool({
    id: "cloudflare-web-analytics",
    name: "Cloudflare Web Analytics",
    stageIds: ["analytics", "iterate"],
    categories: ["traffic-analytics"],
    officialUrl: "https://developers.cloudflare.com/web-analytics/",
    freeTierSummary: "Cloudflare 提供隐私友好的基础 Web Analytics。",
    limitations: ["不替代完整产品事件、用户路径和留存分析。"],
    upgradeSignals: ["需要产品漏斗、用户分群和行为回放。"],
    alternatives: ["posthog"],
    sources: [{ label: "Cloudflare Web Analytics", url: "https://developers.cloudflare.com/web-analytics/" }],
  }),
  tool({
    id: "posthog",
    name: "PostHog",
    stageIds: ["analytics", "iterate"],
    categories: ["product-analytics", "feature-flags"],
    officialUrl: "https://posthog.com/pricing",
    freeTierSummary: "免费额度覆盖早期产品事件与基础分析，具体配额按官方定价核验。",
    limitations: ["错误事件设计会产生噪声和不必要的数据成本。"],
    upgradeSignals: ["事件量、回放、数据保留或团队协作超过免费额度。"],
    alternatives: ["cloudflare-web-analytics"],
    sources: [{ label: "PostHog Pricing", url: "https://posthog.com/pricing" }],
  }),
  tool({
    id: "sentry",
    name: "Sentry",
    stageIds: ["analytics", "iterate"],
    categories: ["error-monitoring"],
    officialUrl: "https://sentry.io/pricing/",
    freeTierSummary: "Developer 免费方案适合早期错误监控，配额按官方定价核验。",
    limitations: ["敏感数据必须在采集前过滤；事件量可能快速增长。"],
    upgradeSignals: ["需要更长保留、更高事件量或团队级可观测性。"],
    alternatives: ["posthog"],
    sources: [{ label: "Sentry Pricing", url: "https://sentry.io/pricing/" }],
  }),
  tool({
    id: "resend",
    name: "Resend",
    stageIds: ["automation"],
    categories: ["transactional-email"],
    officialUrl: "https://resend.com/pricing",
    freeTierSummary: "免费方案适合早期交易邮件，发送量和每日限制按官方页面核验。",
    limitations: ["生产发送需要域名验证、退信处理和合规退订策略。"],
    upgradeSignals: ["邮件量、团队权限或数据保留超出免费方案。"],
    alternatives: ["n8n", "make"],
    sources: [{ label: "Resend Pricing", url: "https://resend.com/pricing" }],
  }),
  tool({
    id: "n8n",
    name: "n8n",
    stageIds: ["automation"],
    categories: ["workflow-automation"],
    officialUrl: "https://n8n.io/pricing/",
    freeTierSummary: "自托管 Community Edition 可用；Cloud 方案和试用按官方定价核验。",
    limitations: ["自托管意味着自行负责升级、备份、安全和可用性。"],
    upgradeSignals: ["维护成本超过托管方案费用或需要企业治理。"],
    alternatives: ["make", "github-actions"],
    sources: [{ label: "n8n Pricing", url: "https://n8n.io/pricing/" }],
  }),
  tool({
    id: "make",
    name: "Make",
    stageIds: ["automation"],
    categories: ["workflow-automation"],
    officialUrl: "https://www.make.com/en/pricing",
    freeTierSummary: "免费方案提供有限月度 credits，适合验证简单自动化。",
    limitations: ["高频轮询和复杂场景会快速消耗 credits。"],
    upgradeSignals: ["执行频率、数据量或高级连接器超过免费限制。"],
    alternatives: ["n8n", "github-actions"],
    sources: [{ label: "Make Pricing", url: "https://www.make.com/en/pricing" }],
  }),
  tool({
    id: "github-actions",
    name: "GitHub Actions",
    stageIds: ["build", "deploy", "automation"],
    categories: ["ci-cd", "scheduled-jobs"],
    officialUrl: "https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions",
    freeTierSummary: "公开仓库和 Free 方案包含一定的 Actions 使用额度。",
    limitations: ["私有仓库分钟数、存储和并发受方案限制。"],
    upgradeSignals: ["构建分钟、制品存储或并发成为交付瓶颈。"],
    alternatives: ["cloudflare-pages", "n8n"],
    sources: [{ label: "GitHub Actions Billing", url: "https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions" }],
  }),
]
